version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: ledger-wallet-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: ledger_wallet

  redis:
    image: redis:7
    container_name: ledger-wallet-redis
    ports:
      - "6379:6379"